CREATE TABLE Alunos
(ID INT,
 Nome VARCHAR2(30),
 Valor INT);
 
INSERT INTO Alunos VALUES (1,'Julia',81);
INSERT INTO Alunos VALUES (2,'Carol',68);
INSERT INTO Alunos VALUES (3,'Maria',99);
INSERT INTO Alunos VALUES (4,'Andreia',78);
INSERT INTO Alunos VALUES (5,'Jaqueline',63);
INSERT INTO Alunos VALUES (6,'Marcela',88);
 
CREATE TABLE Notas(
Nota INT,
Valor_Min INT,
Valor_Max INT);

INSERT INTO Notas VALUES (1,0,9);
INSERT INTO Notas VALUES (2,10,19);
INSERT INTO Notas VALUES (3,20,29);
INSERT INTO Notas VALUES (4,30,39);
INSERT INTO Notas VALUES (5,40,49);
INSERT INTO Notas VALUES (6,50,59);
INSERT INTO Notas VALUES (7,60,69);
INSERT INTO Notas VALUES (8,70,79);
INSERT INTO Notas VALUES (9,80,89);
INSERT INTO Notas VALUES (10,90,100);


SELECT 	CASE WHEN (Nota<8) THEN NULL ELSE Nome END AS Nome, Nota,Valor 
FROM 	Alunos, Notas 
WHERE   Valor BETWEEN  Valor_Min AND Valor_Max 
ORDER BY Nota DESC,CASE WHEN (Nome IS NOT NULL)	 THEN Valor END DESC,
		CASE WHEN (Nome IS NOT NULL)	 THEN Nome END ASC,
		CASE WHEN (Nome IS NULL) THEN Valor END ASC;
		
		